# Generated by Django 5.2.1 on 2025-06-08 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_side_id', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file_id', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('thumbnail_url', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temporary', models.BooleanField(default=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.users')),
            ],
        ),
    ]
