# Generated by Django 5.2.1 on 2026-02-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='post_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
